  File "telebot_linux.py", line 12
SyntaxError: Non-ASCII character '\xed' in file telebot_linux.py on line 12, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
